In [1]:
import pandas as pd
import numpy as np

In [19]:
data = pd.ExcelFile('../data/datos.xlsx')

## Consumo

In [7]:
cocaina = {
    'Australia': 2.73,
    'Albania': 2.5,
    'Escocia': 2.41,
    'Inglaterra y Gales': 2.36,
    'Estados Unidos': 2.31,
    'España': 2.27,
    'Brasil': 2.18,
    'Países Bajos': 2.18,
    'Uruguay': 2.0,
    'Irlanda': 1.8,
    'Ecuador': 1.69,
    'Reino Unido (Irlanda del Norte)': 1.65,
    'Canadá': 1.47,
    'Austria': 1.41,
    'Chile': 1.25,
    'Guatemala': 1.25,
    'Dinamarca': 1.23,
    'Francia': 1.23,
    'Costa Rica': 1.21,
    'Argentina': 1.2,
    'Malta': 1.14,
    'Nueva Zelanda': 1.1,
    'Italia': 1.08,
    'Croacia': 1.07,
    'Estonia': 1.03,
    'Alemania': 1.03,
    'Noruega': 1.03,
    'Suecia': 1.03,
    'Sudáfrica': 1.02,
    'Bélgica': 1.0,
    'Islandia': 0.99,
    'Jamaica': 0.98,
    'Montenegro': 0.98,
    'Finlandia': 0.8,
    'Venezuela': 0.73,
    'Suiza': 0.71,
    'Perú': 0.68,
    'Letonia': 0.67,
    'Colombia': 0.66,
    'México': 0.65,
    'Eslovenia': 0.65,
    'Santa Lucía': 0.6,
    'Costa de Marfil': 0.59,
    'Macedonia': 0.58,
    'Polonia': 0.56,
    'Haití': 0.54,
    'Bolivia': 0.49,
    'Trinidad y Tobago': 0.48,
    'Luxemburgo': 0.45,
    'Marruecos': 0.43,
    'Ucrania': 0.42,
    'Grecia': 0.4,
    'Israel': 0.4,
    'Bulgaria': 0.37,
    'El Salvador': 0.37,
    'Egipto': 0.35,
    'Chipre': 0.33,
    'República Dominicana': 0.32,
    'Chequia': 0.3,
    'Hungría': 0.3,
    'Lituania': 0.3,
    'Rumania': 0.25,
    'Surinam': 0.25,
    'Eslovaquia': 0.23,
    'Cabo Verde': 0.2,
    'Portugal': 0.2,
    'Irán': 0.11,
    'India': 0.1,
    'Kenia': 0.1,
    'Panamá': 0.1,
    'Serbia': 0.1,
    'Túnez': 0.1,
    'Nigeria': 0.09,
    'Tailandia': 0.07,
    'Filipinas': 0.06,
    'Bahamas': 0.05,
    'Georgia': 0.05,
    'Turquía': 0.05,
    'Japón': 0.04,
    'Maldivas': 0.04,
    'Argelia': 0.01,
    'Indonesia': 0.01,
    'Pakistán': 0.01
}

In [8]:
cannabis = {
    'Israel': 20.5,
    'Estados Unidos': 18.09,
    'Canadá': 14.1,
    'Nueva Zelanda': 13.83,
    'Jamaica': 12.61,
    'Australia': 10.8,
    'Chile': 10.78,
    'Uruguay': 10.73,
    'Marruecos': 10.47,
    'Francia': 10.44,
    'España': 10.07,
    'Chequia': 9.41,
    'Países Bajos': 9.32,
    'Santa Lucía': 8.87,
    'Italia': 8.55,
    'Croacia': 7.7,
    'Finlandia': 7.15,
    'Suiza': 6.95,
    'Irlanda': 6.93,
    'Inglaterra y Gales': 6.92,
    'Escocia': 6.85,
    'Alemania': 6.62,
    'Estonia': 6.59,
    'Austria': 6.35,
    'Dinamarca': 6.25,
    'Bélgica': 5.8,
    'Argentina': 5.67,
    'Albania': 5.6,
    'Islandia': 5.27,
    'Eslovenia': 5.15,
    'Luxemburgo': 5.1,
    'Reino Unido (Irlanda del Norte)': 4.85,
    'Polonia': 4.84,
    'Noruega': 4.66,
    'Egipto': 4.6,
    'Trinidad y Tobago': 4.41,
    'Eslovaquia': 4.28,
    'Costa Rica': 4.12,
    'Letonia': 4.03,
    'Georgia': 4.0,
    'Túnez': 3.97,
    'Macedonia': 3.86,
    'Sudáfrica': 3.65,
    'Pakistán': 3.6,
    'Portugal': 3.53,
    'Guatemala': 3.48,
    'Surinam': 3.4,
    'Bulgaria': 3.37,
    'Suecia': 3.27,
    'Costa de Marfil': 3.24,
    'Lituania': 3.1,
    'Bahamas': 3.1,
    'Colombia': 2.98,
    'India': 2.83,
    'Brasil': 2.81,
    'Grecia': 2.8,
    'Chipre': 2.8,
    'Montenegro': 2.77,
    'Maldivas': 2.55,
    'Ucrania': 2.51,
    'Cabo Verde': 2.4,
    'Rumania': 2.25,
    'El Salvador': 2.03,
    'Malta': 2.0,
    'Haití': 2.0,
    'Serbia': 1.8,
    'México': 1.65,
    'Bolivia': 1.63,
    'Venezuela': 1.48,
    'Hungría': 1.42,
    'Tailandia': 1.33,
    'Perú': 1.31,
    'Kenia': 1.2,
    'Filipinas': 1.12,
    'Turquía': 0.84,
    'Panamá': 0.77,
    'Indonesia': 0.76,
    'República Dominicana': 0.68,
    'Ecuador': 0.67,
    'Argelia': 0.52,
    'Irán': 0.45,
    'Japón': 0.14
}

In [9]:
metanfetaminas = {
    'Haití': 6.1,
    'Estados Unidos': 2.42,
    'Australia': 1.73,
    'Tailandia': 1.67,
    'Países Bajos': 1.64,
    'Finlandia': 1.48,
    'Austria': 1.35,
    'Brasil': 1.23,
    'Croacia': 1.2,
    'Alemania': 1.15,
    'Islandia': 1.04,
    'Polonia': 1.04,
    'Escocia': 1.03,
    'Nueva Zelanda': 1.03,
    'Estonia': 0.94,
    'Filipinas': 0.94,
    'Jamaica': 0.81,
    'Reino Unido (Irlanda del Norte)': 0.8,
    'Canadá': 0.74,
    'Bulgaria': 0.72,
    'Suecia': 0.71,
    'Israel': 0.7,
    'Dinamarca': 0.67,
    'España': 0.63,
    'Irán': 0.62,
    'Costa de Marfil': 0.61,
    'Inglaterra y Gales': 0.6,
    'Chequia': 0.6,
    'Irlanda': 0.57,
    'Ucrania': 0.51,
    'Noruega': 0.5,
    'Montenegro': 0.49,
    'Malta': 0.47,
    'Eslovenia': 0.47,
    'Bélgica': 0.43,
    'Hungría': 0.43,
    'Italia': 0.4,
    'Letonia': 0.4,
    'Suiza': 0.38,
    'El Salvador': 0.38,
    'Indonesia': 0.35,
    'Eslovaquia': 0.32,
    'Francia': 0.27,
    'Venezuela': 0.26,
    'Lituania': 0.23,
    'México': 0.21,
    'Macedonia': 0.2,
    'India': 0.18,
    'Chipre': 0.17,
    'Serbia': 0.15,
    'Chile': 0.14,
    'Japón': 0.13,
    'Uruguay': 0.11,
    'Albania': 0.1,
    'Bolivia': 0.1,
    'Luxemburgo': 0.1,
    'Maldivas': 0.1,
    'Nigeria': 0.09,
    'Rumania': 0.08,
    'Pakistán': 0.08,
    'Argelia': 0.03,
    'Portugal': 0.02,
    'Turquía': 0.02
}

In [10]:
opioides = {
    'Serbia': 5.15,
    'Estados Unidos': 5.03,
    'Nigeria': 4.66,
    'Australia': 3.1,
    'Irán': 3.02,
    'Uruguay': 2.54,
    'India': 2.06,
    'Egipto': 2.0,
    'Pakistán': 1.55,
    'Maldivas': 1.46,
    'Costa Rica': 1.41,
    'Chile': 1.04,
    'Italia': 1.0,
    'Jamaica': 1.0,
    'Suecia': 0.94,
    'Nueva Zelanda': 0.91,
    'Estonia': 0.85,
    'Georgia': 0.71,
    'Irlanda': 0.67,
    'Brasil': 0.64,
    'Finlandia': 0.64,
    'Dinamarca': 0.58,
    'Austria': 0.55,
    'Francia': 0.53,
    'Letonia': 0.53,
    'Sudáfrica': 0.5,
    'Macedonia': 0.5,
    'Bulgaria': 0.44,
    'Lituania': 0.43,
    'Luxemburgo': 0.38,
    'Bélgica': 0.37,
    'Alemania': 0.36,
    'Malta': 0.34,
    'Eslovenia': 0.33,
    'Croacia': 0.31,
    'Colombia': 0.28,
    'España': 0.27,
    'Rumania': 0.25,
    'México': 0.24,
    'Eslovaquia': 0.21,
    'Haití': 0.2,
    'Argentina': 0.19,
    'Chipre': 0.19,
    'Chequia': 0.16,
    'El Salvador': 0.14,
    'República Dominicana': 0.14,
    'Israel': 0.1,
    'Ecuador': 0.06,
    'Filipinas': 0.05,
    'Marruecos': 0.02
}

In [14]:
import pandas as pd
import numpy as np

# Crear lista de todos los países únicos
paises = set(list(cocaina.keys()) + list(cannabis.keys()) + 
             list(metanfetaminas.keys()) + list(opioides.keys()))
paises = sorted(paises)

# Construir el DataFrame
data = []
for pais in paises:
    fila = {
        'País': pais,
        'Cocaína': cocaina.get(pais, pd.NA),
        'Cannabis': cannabis.get(pais, pd.NA),
        'Metanfetaminas': metanfetaminas.get(pais, pd.NA),
        'Opioides': opioides.get(pais, pd.NA)
    }
    data.append(fila)

df = pd.DataFrame(data)

# Función para aplicar categorías
def aplicar_categorias(df):
    categorizadores = {
        'Cocaína': [
            (1.2, 'Alta'),
            (0.6, 'Media'),
            (0.29, 'Baja'),
            (-np.inf, 'Muy baja')
        ],
        'Cannabis': [
            (6.8, 'Alta'),
            (3.9, 'Media'),
            (2.3, 'Baja'),
            (-np.inf, 'Muy baja')
        ],
        'Metanfetaminas': [
            (0.9, 'Alta'),
            (0.48, 'Media'),
            (0.17, 'Baja'),
            (-np.inf, 'Muy Baja')
        ],
        'Opioides': [
            (1, 'Alta'),
            (0.5, 'Media'),
            (0.26, 'Baja'),
            (-np.inf, 'Muy baja')
        ]
    }
    
    for droga, limites in categorizadores.items():
        col_categoria = f'Categoría_{droga}'
        # Ordenar límites de mayor a menor
        limites_ordenados = sorted(limites, key=lambda x: x[0], reverse=True)
        df[col_categoria] = df[droga].apply(
            lambda x: next((cat for lim, cat in limites_ordenados if pd.notna(x) and x > lim), pd.NA)
        )
    
    return df

# Aplicar categorías
df = aplicar_categorias(df)

# Reordenar columnas
columnas = ['País',
            'Cocaína', 'Categoría_Cocaína',
            'Cannabis', 'Categoría_Cannabis',
            'Metanfetaminas', 'Categoría_Metanfetaminas',
            'Opioides', 'Categoría_Opioides']

df_consumo = df[columnas]

In [15]:
df_consumo

,País,Cocaína,Categoría_Cocaína,Cannabis,Categoría_Cannabis,Metanfetaminas,Categoría_Metanfetaminas,Opioides,Categoría_Opioides
0,Albania,2.50,Alta,5.6,Media,0.1,Muy Baja,<NA>,<NA>
1,Alemania,1.03,Media,6.62,Media,1.15,Alta,0.36,Baja
2,Argelia,0.01,Muy baja,0.52,Muy baja,0.03,Muy Baja,<NA>,<NA>
3,Argentina,1.20,Media,5.67,Media,<NA>,<NA>,0.19,Muy baja
4,Australia,2.73,Alta,10.8,Alta,1.73,Alta,3.1,Alta
...,...,...,...,...,...,...,...,...,...
78,Turquía,0.05,Muy baja,0.84,Muy baja,0.02,Muy Baja,<NA>,<NA>
79,Túnez,0.10,Muy baja,3.97,Media,<NA>,<NA>,<NA>,<NA>
80,Ucrania,0.42,Baja,2.51,Baja,0.51,Media,<NA>,<NA>
81,Uruguay,2.00,Alta,10.73,Alta,0.11,Muy Baja,2.54,Alta
82,Venezuela,0.73,Media,1.48,Muy baja,0.26,Baja,<NA>,<NA>

In [17]:
df_consumo.to_csv('../data/consumo.csv', index=False)

## Produccion

In [15]:
import pandas as pd

# Datos crudos (copiar exactamente los datos que proporcionaste)
cocaina_raw = [
    ('Colombia', 24514, 'ALTA'), ('Bolivia', 3446, None), ('Peru', 2202, None),
    # ... (copiar todos los registros de cocaína que mostraste)
]

opioides_raw = [
    ('Malasia', 40, 'ALTA'), ('Grecia', 22, None), ('República Checa', 19, None),
    # ... (copiar todos los registros de opioides que mostraste)
]

metanfetaminas_raw = [
    ('Estados Unidos', 2806, 'ALTA'), ('República Checa', 1021, None), ('China', 479, None),
    # ... (copiar todos los registros de metanfetaminas que mostraste)
]

# Función para crear DataFrame base
def crear_dataframe():
    paises = set([p[0] for p in cocaina_raw + opioides_raw + metanfetaminas_raw])
    data = []
    
    for pais in paises:
        row = {'País': pais}
        
        # Buscar en cada lista
        for lista, sufijo in zip([cocaina_raw, opioides_raw, metanfetaminas_raw], ['_coca', '_opio', '_meta']):
            match = next((x for x in lista if x[0] == pais), (None, None, None))
            row[f'laboratorio{sufijo}'] = match[1]
        
        data.append(row)
    
    return pd.DataFrame(data).replace({None: pd.NA})

df = crear_dataframe()

# Funciones de categorización (las que proporcionaste)
def asignar_categoria_coca(x):
    if x > 70: return "ALTA"
    elif x > 12: return "MEDIA"
    elif x > 1: return "BAJA"
    else: return "MUY BAJA"

def asignar_categoria_opio(x):
    if x > 18: return "ALTA"
    elif x > 8: return "MEDIA"
    elif x > 2: return "BAJA"
    else: return "MUY BAJA"

def asignar_categoria_meta(x):
    if x > 37: return "ALTA"
    elif x > 8: return "MEDIA"
    elif x > 2: return "BAJA"
    else: return "MUY BAJA"

# Aplicar categorización automática
def aplicar_categorias(df):
    for droga, func in zip(['coca', 'opio', 'meta'], 
                          [asignar_categoria_coca, asignar_categoria_opio, asignar_categoria_meta]):
        col_lab = f'laboratorio_{droga}'
        col_cat = f'cat_{droga}'
        
        df[col_cat] = df[col_lab].apply(
            lambda x: func(x).title() if pd.notna(x) else 'Sin dato'
        )
    return df

# Resultado final
df_final = aplicar_categorias(df)[[
    'País', 
    'laboratorio_coca', 'cat_coca',
    'laboratorio_opio', 'cat_opio',
    'laboratorio_meta', 'cat_meta'
]].sort_values('País').reset_index(drop=True)

In [18]:
import pandas as pd
import numpy as np

# Diccionarios actualizados
cocaina = {
    'Colombia': 24514, 'Bolivia': 3446, 'Peru': 2202, 'Argentina': 287,
    'Venezuela': 271, 'Chile': 147, 'China': 73, 'Honduras': 51,
    'España': 46, 'Países Bajos': 42, 'Belgica': 22, 'Guatemala': 13,
    'Paraguay': 12, 'Grecia': 12, 'Ecuador': 11, 'Australia': 10,
    'Brasil': 9, 'Suecia': 2, 'Mexico': 1, 'Panama': 1, 'Alemania': 1,
    'Polonia': 1, 'Rumania': 1, 'Senegal': 1, 'Sudafrica': 1, 'Costa de marfil': 1
}

opioides = {
    'Malaysia': 40, 'Grecia': 22, 'Chequia': 19, 'China': 19,
    'Mexico': 14, 'India': 14, 'Francia': 10, 'Nueva Zelandia': 10,
    'Estados Unidos': 9, 'Myanmar': 8, 'Colombia': 6, 'Australia': 6,
    'Países Bajos': 5, 'Canada': 3, 'Belgica': 2, 'España': 2,
    'Argentina': 1, 'Alemania': 1, 'Estonia': 1
}

metanfetaminas = {
    'Estados Unidos': 2806, 'Chequia': 1021, 'China': 479, 'Australia': 308,
    'New Zealand': 297, 'Mexico': 191, 'Países Bajos': 62, 'Polonia': 48,
    'Alemania': 38, 'Eslovaquia': 32, 'Canada': 26, 'Malasia': 25,
    'Austria': 23, 'Bélgica': 22, 'Sudáfrica': 20, 'Indonesia': 16,
    'Ucrania': 14, 'Filipinas': 9, 'Nigeria': 8, 'España': 6, 'Myanmar': 6,
    'Francia': 5, 'Argentina': 4, 'Bielorrusia': 3, 'Bulgaria': 3,
    'Federación Rusa': 3, 'Grecia': 3, 'Hungría': 2, 'Lituania': 2,
    'Portugal': 2, 'Suecia': 2, 'Chipre': 1, 'Eslovenia': 1, 'Irlanda': 1,
    'Italia': 1, 'Mozambique': 1, 'India': 1
}

# Recopilar todos los países únicos
todos_paises = set(list(cocaina.keys()) + list(opioides.keys()) + list(metanfetaminas.keys()))
todos_paises = sorted(todos_paises)

# Crear DataFrame
data = []
for pais in todos_paises:
    data.append({
        'País': pais,
        'Cocaína': cocaina.get(pais, np.nan),
        'Opioides': opioides.get(pais, np.nan),
        'Metanfetaminas': metanfetaminas.get(pais, np.nan)
    })

df = pd.DataFrame(data)

# Funciones de categorización actualizadas
def asignar_categoria_coca(x):
    if pd.isna(x): return np.nan
    if x > 70: return "ALTA"
    elif x > 12: return "MEDIA"
    elif x > 1: return "BAJA"
    else: return "MUY BAJA"

def asignar_categoria_opio(x):
    if pd.isna(x): return np.nan
    if x > 18: return "ALTA"
    elif x > 8: return "MEDIA"
    elif x > 2: return "BAJA"
    else: return "MUY BAJA"

def asignar_categoria_meta(x):
    if pd.isna(x): return np.nan
    if x > 37: return "ALTA"
    elif x > 8: return "MEDIA"
    elif x > 2: return "BAJA"
    else: return "MUY BAJA"

# Aplicar categorizaciones
df['Categoría_Cocaína'] = df['Cocaína'].apply(asignar_categoria_coca)
df['Categoría_Opioides'] = df['Opioides'].apply(asignar_categoria_opio)
df['Categoría_Metanfetaminas'] = df['Metanfetaminas'].apply(asignar_categoria_meta)

# Reordenar columnas
df_produccion = df[['País', 
         'Cocaína', 'Categoría_Cocaína',
         'Opioides', 'Categoría_Opioides',
         'Metanfetaminas', 'Categoría_Metanfetaminas']]

In [20]:
df_produccion.head()

,País,Cocaína,Categoría_Cocaína,Opioides,Categoría_Opioides,Metanfetaminas,Categoría_Metanfetaminas
0,Alemania,1.0,MUY BAJA,1.0,MUY BAJA,38.0,ALTA
1,Argentina,287.0,ALTA,1.0,MUY BAJA,4.0,BAJA
2,Australia,10.0,BAJA,6.0,BAJA,308.0,ALTA
3,Austria,NaN,NaN,NaN,NaN,23.0,MEDIA
4,Belgica,22.0,MEDIA,2.0,MUY BAJA,NaN,NaN

In [22]:
df_produccion.to_csv('../data/produccion.csv', index=False)

## Trafico

In [20]:
df_trafico = data.parse('Tráfico', header=None)

df_trafico_clean = df_trafico.dropna(how='all')

header_row = 1  # La fila REAL con los encabezados es la 1 (índice 1)
df_trafico_clean.columns = ['Col_extra', 'País', 'Cocaína', 'Cannabis', 'Metanfetaminas', 'Heroína']

df_trafico_clean = df_trafico_clean.drop(columns=['Col_extra'])

df_trafico_final = df_trafico_clean.iloc[2:].copy()

df_trafico_final = df_trafico_final.reset_index(drop=True)
df_trafico_final['País'] = df_trafico_final['País'].str.strip()

def limpiar_valores(valor):
    if isinstance(valor, str):
        try:
            return float(valor.replace('$', '').replace(',', '').strip())
        except:
            return np.nan
    return valor

for col in ['Cocaína', 'Cannabis', 'Metanfetaminas', 'Heroína']:
    df_trafico_final[col] = df_trafico_final[col].apply(limpiar_valores)

In [21]:
df_trafico_final.head(10)

          País        Cocaína  Cannabis  Metanfetaminas        Heroína
0    Sri Lanka  177609.980000   1731.53     4567.113736  145917.640000
1    Australia  159530.390000       NaN    85635.359116  142964.640000
2    Finlandia   94686.555524   5751.15    14874.141876   53374.333333
3    Palestina   75000.000000   4464.29             NaN            NaN
4     Moldavia   71174.380000       NaN             NaN  126448.890000
5      Estonia   71174.380000   7278.84     4744.960000            NaN
6       Egipto   63836.580000   2168.57    31709.791984    6341.960000
7        India   59666.680000    753.22     9763.638583  191331.410000
8      Austria   59471.364769       NaN    47449.580000   37402.217251
9  Reino Unido   57087.631986   2562.87    44987.146530   33375.054519

In [22]:
df_trafico_final.to_csv('../data/trafico.csv', index=False)

## Mercado

In [23]:
df_mercado = data.parse('Estimación de Mercado', header=None)
df_mercado_clean = df_mercado.dropna(how='all', axis=0)


def procesar_columna_ajustada(df, start_col):
    tabla = df.iloc[1:, start_col:start_col+2].copy()  
    tabla.columns = ['País', df.iloc[3, start_col+1]]  
    tabla = tabla.dropna(subset=['País'])
    return tabla.reset_index(drop=True)


poblacion = procesar_columna_ajustada(df_mercado_clean, 1).rename(
    columns={df_mercado_clean.iloc[3,2]: 'Población'})

consumo = procesar_columna_ajustada(df_mercado_clean, 4).rename(
    columns={df_mercado_clean.iloc[3,5]: 'Consumo_Tn'})

mercado = procesar_columna_ajustada(df_mercado_clean, 7).rename(
    columns={df_mercado_clean.iloc[3,8]: 'Mercado_USD'})

def limpiar_final(df):
    df['País'] = df['País'].astype(str).str.strip()
    df = df.replace({
        'Reino Unido (Irlanda del Norte)': 'Reino Unido',
        'Chequia': 'República Checa',
        'México': 'México' 
    })
    if 'Mercado_USD' in df.columns:
        df['Mercado_USD'] = df['Mercado_USD'].astype(str).str.replace('[$,]', '', regex=True).replace('nan', np.nan).astype(float)
    return df

df_final = (
    limpiar_final(poblacion)
    .merge(limpiar_final(consumo), on='País', how='outer')
    .merge(limpiar_final(mercado), on='País', how='outer')
    .sort_values('Población', ascending=False)
    .reset_index(drop=True)
)

df_final[['Población', 'Consumo_Tn']] = df_final[['Población', 'Consumo_Tn']].apply(pd.to_numeric, errors='coerce')

In [24]:
df_final.head(10)

             País  Población  Consumo_Tn   Mercado_USD
0  Estados Unidos    7409071  614.952893  1.875606e+10
1          Brasil    4488953  372.583099  9.314577e+08
2           India    1300000  107.900000  6.438035e+09
3          España    1056208   87.665264  3.748080e+09
4        Alemania     831375   69.004125  3.039619e+09
5         Francia     795088   65.992304  2.544187e+09
6          México     784635   65.124705  6.643807e+08
7       Australia     668847   55.514301  8.856218e+09
8          Italia     656593   54.497219  2.396256e+09
9       Argentina     506004   41.998332  2.099917e+08

In [25]:
df_final.to_csv('../data/mercado.csv', index=False)